import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:equatable/equatable.dart';

// Published status of a work (live vs draft)
enum WorkStatus { draft, published }

// Top-level model for a single musical work
class Work {
  final String id;
  final String title;
  final String year;
  final String subtitle;
  final String instrumentation;
  final String duration;
  final int order;
  final List<String> categories;
  final List<WorkDetail> details;
  final bool hasDataIntegrityIssue;
  final WorkStatus status; // persisted as 'currentStatus'
  final bool isVisible; // controls public visibility
  final bool hasDraft; // whether a draft map exists on the doc
    // When true, keep the title's original casing in the public UI.
    // When false (default), display the title in ALL CAPS.
    final bool allowMixedCaseTitle;

  Work({
    required this.id,
    required this.title,
    required this.year,
    required this.subtitle,
    required this.instrumentation,
    required this.duration,
    required this.order,
    this.categories = const [],
    this.details = const [],
    this.hasDataIntegrityIssue = false,
    this.status = WorkStatus.published,
    this.isVisible = true,
    this.hasDraft = false,
    this.allowMixedCaseTitle = false,
  });

  factory Work.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    final String rawStatus = (data['currentStatus'] ?? 'published').toString();
    final WorkStatus status = rawStatus == 'draft' ? WorkStatus.draft : WorkStatus.published;
    final bool hasDraft = data.containsKey('draft') && data['draft'] != null;
    return Work(
      id: doc.id,
      title: (data['title'] ?? '[Title Missing]').toString(),
      year: (data['year'] ?? '').toString(),
      subtitle: (data['subtitle'] ?? '').toString(),
      instrumentation: (data['instrumentation'] ?? '').toString(),
      duration: (data['duration'] ?? '').toString(),
      order: data['order'] ?? 0,
      categories: List<String>.from(data['categories'] ?? []),
      details: (data['details'] as List<dynamic>?)
              ?.map((detailData) =>
                  WorkDetail.fromMap(detailData as Map<String, dynamic>))
              .toList() ??
          [],
      hasDataIntegrityIssue: (data['hasDataIntegrityIssue'] ?? false) == true,
      status: status,
      isVisible: (data['isVisible'] ?? true) == true,
      hasDraft: hasDraft,
      allowMixedCaseTitle: (data['allowMixedCaseTitle'] ?? false) == true,
    );
  }

  // Build Work from a raw map (e.g., a draft sub-map) and explicit id.
  factory Work.fromDataMap({required String id, required Map<String, dynamic> data}) {
    final String rawStatus = (data['currentStatus'] ?? 'draft').toString();
    final WorkStatus status = rawStatus == 'published' ? WorkStatus.published : WorkStatus.draft;
    return Work(
      id: id,
      title: (data['title'] ?? '[Title Missing]').toString(),
      year: (data['year'] ?? '').toString(),
      subtitle: (data['subtitle'] ?? '').toString(),
      instrumentation: (data['instrumentation'] ?? '').toString(),
      duration: (data['duration'] ?? '').toString(),
      order: data['order'] ?? 0,
      categories: List<String>.from(data['categories'] ?? []),
      details: (data['details'] as List<dynamic>?)
              ?.map((detailData) => WorkDetail.fromMap(detailData as Map<String, dynamic>))
              .toList() ??
          [],
      hasDataIntegrityIssue: (data['hasDataIntegrityIssue'] ?? false) == true,
      status: status,
      isVisible: (data['isVisible'] ?? true) == true,
      hasDraft: (data.containsKey('draft') && data['draft'] != null),
      allowMixedCaseTitle: (data['allowMixedCaseTitle'] ?? false) == true,
    );
  }
  
  // New factory constructor for mapping from source data
  factory Work.fromSource({
    required String title,
    required String year,
    String? subtitle,
    String? instrumentation,
    String? duration,
    List<String>? categories, // Added categories parameter
    List<WorkDetail>? details,
    bool hasDataIntegrityIssue = false,
  }) {
    return Work(
      id: '', // ID will be generated by Firestore upon saving
      title: title,
      year: year,
      subtitle: subtitle ?? '',
      instrumentation: instrumentation ?? '',
      duration: duration ?? '',
      order: 0, // Default order for new works
      categories: categories ?? [], // Use the passed categories
      details: details ?? [],
      hasDataIntegrityIssue: hasDataIntegrityIssue,
      status: WorkStatus.draft,
      isVisible: true,
      hasDraft: false,
      allowMixedCaseTitle: false,
    );
  }


  Map<String, dynamic> toJson() {
    return {
      'title': title,
      'year': year,
      'subtitle': subtitle,
      'instrumentation': instrumentation,
      'duration': duration,
      'order': order,
      'categories': categories,
      'details': details.map((detail) => detail.toJson()).toList(),
      'hasDataIntegrityIssue': hasDataIntegrityIssue,
      'currentStatus': status.name,
      'isVisible': isVisible,
      'allowMixedCaseTitle': allowMixedCaseTitle,
    };
  }
}

// Represents a single piece of detail about a work
class WorkDetail {
  final String id;
  final int order;
  final DisplayType displayType;
  final ButtonStyle buttonStyle;
  final String buttonText;
  final DetailType detailType;
  final dynamic content;
  final bool isCorrupted;
  final bool isTitleVisible;
  // Controls inline detail title visibility. Only used when displayType == inline.
  // Nullable in schema; treat null as false in UI/rendering.
  final bool? isVisibleDetailTitle;
  final double? width;
  final double? height;
  final String? storagePath;

  WorkDetail({
    required this.id,
    required this.order,
    required this.displayType,
    required this.buttonStyle,
    required this.buttonText,
    required this.detailType,
    this.content,
    this.isCorrupted = false,
    this.isTitleVisible = true,
    this.isVisibleDetailTitle,
    this.width,
    this.height,
    this.storagePath,
  });

  factory WorkDetail.fromMap(Map<String, dynamic> map) {
    bool isCorrupted = false;
    final String idFromMap = map['id'] ?? '';
    String buttonTextFromMap = map['buttonText'] ?? '';

    final String displayTypeString = (map['displayType'] ?? '').toString();
    final String buttonStyleString = (map['buttonStyle'] ?? '').toString();
    final String detailTypeString = (map['detailType'] ?? '').toString();

    final displayType = DisplayType.values.firstWhere(
      (e) => e.toString() == displayTypeString,
      orElse: () {
        isCorrupted = true;
        return DisplayType.button;
      },
    );

    if (displayType == DisplayType.button && buttonTextFromMap.isEmpty) {
      buttonTextFromMap = '[Button Text Missing]';
      isCorrupted = true;
    } else if (displayType == DisplayType.inline && buttonTextFromMap.isEmpty) {
      buttonTextFromMap = '[Title Missing]';
    }

    final buttonStyle = ButtonStyle.values.firstWhere(
      (e) => e.toString() == buttonStyleString,
      orElse: () {
        isCorrupted = true;
        return ButtonStyle.secondary;
      },
    );
    
    final detailType = DetailType.values.firstWhere(
      (e) => e.toString() == detailTypeString,
      orElse: () {
        isCorrupted = true;
        return DetailType.link;
      },
    );

    return WorkDetail(
      id: idFromMap.isNotEmpty ? idFromMap : FirebaseFirestore.instance.collection('tmp').doc().id,
      order: map['order'] ?? 0,
      displayType: displayType,
      buttonStyle: buttonStyle,
      buttonText: buttonTextFromMap,
      detailType: detailType,
      content: _parseContent(map['content'], detailType),
      isCorrupted: isCorrupted,
      isTitleVisible: map['isTitleVisible'] ?? true,
      isVisibleDetailTitle: map.containsKey('isVisibleDetailTitle')
          ? (map['isVisibleDetailTitle'] as bool?)
          : null,
      width: (map['width'] as num?)?.toDouble(),
      height: (map['height'] as num?)?.toDouble(),
      storagePath: map['storagePath'] as String?,
    );
  }

  factory WorkDetail.empty() {
    return WorkDetail(
      id: FirebaseFirestore.instance.collection('tmp').doc().id,
      order: 0,
      displayType: DisplayType.inline,
      buttonStyle: ButtonStyle.secondary,
      buttonText: '',
      detailType: DetailType.richText,
      content: const {'ops': []},
      isTitleVisible: true,
      // Default new inline items to hide inline title unless opted-in
      isVisibleDetailTitle: false,
    );
  }

  Map<String, dynamic> toJson() {
    dynamic finalContent;
    if (detailType == DetailType.audio && content is List<AudioClip>) {
      finalContent = content.map((clip) => clip.toJson()).toList();
    } else {
      finalContent = content;
    }
    
    return {
      'id': id,
      'order': order,
      'displayType': displayType.toString(),
      'buttonStyle': buttonStyle.toString(),
      'buttonText': buttonText,
      'detailType': detailType.toString(),
      'content': finalContent,
      'isTitleVisible': isTitleVisible,
      'isVisibleDetailTitle': isVisibleDetailTitle,
      'width': width,
      'height': height,
      'storagePath': storagePath,
    };
  }

  static dynamic _parseContent(dynamic contentData, DetailType type) {
    if (type == DetailType.audio && contentData is List) {
      return contentData
          .map((clipData) =>
              AudioClip.fromMap(clipData as Map<String, dynamic>))
          .toList();
    }
    return contentData;
  }
}

class AudioClip extends Equatable {
  final String fileId; // Document ID from the 'stored_files' collection
  final String title;
  final String url;

  const AudioClip({required this.fileId, required this.title, required this.url});

  factory AudioClip.fromMap(Map<String, dynamic> map) {
    return AudioClip(
      fileId: map['fileId'] ?? '',
      title: map['title'] ?? '',
      url: map['url'] ?? '',
    );
  }

   Map<String, dynamic> toJson() {
    return {
      'fileId': fileId,
      'title': title,
      'url': url,
    };
  }

  AudioClip copyWith({
    String? fileId,
    String? title,
    String? url,
  }) {
    return AudioClip(
      fileId: fileId ?? this.fileId,
      title: title ?? this.title,
      url: url ?? this.url,
    );
  }
  
  @override
  List<Object?> get props => [fileId, title, url];
}

enum DetailType { pdf, audio, link, embed, richText, request, image }
enum DisplayType { button, inline }
enum ButtonStyle { primary, secondary }