import 'package:flutter/material.dart';
import 'package:john_estacio_website/features/discography/domain/models/discography_model.dart';

class EditDiscographyDialog extends StatefulWidget {
  final DiscographyItem? item;

  const EditDiscographyDialog({super.key, this.item});

  @override
  State<EditDiscographyDialog> createState() => _EditDiscographyDialogState();
}

class _EditDiscographyDialogState extends State<EditDiscographyDialog> {
  final _formKey = GlobalKey<FormState>();
  late final TextEditingController _titleController;
  late final TextEditingController _embedController;

  @override
  void initState() {
    super.initState();
    _titleController = TextEditingController(text: widget.item?.title ?? '');
    _embedController = TextEditingController(text: widget.item?.embedHtml ?? '');
  }

  @override
  void dispose() {
    _titleController.dispose();
    _embedController.dispose();
    super.dispose();
  }

  void _onSave() {
    if (_formKey.currentState?.validate() ?? false) {
      final String title = _titleController.text.trim();
      final String embed = _embedController.text.trim();

      // Preserve id and order on edit; provide defaults on add.
      final DiscographyItem result = (widget.item == null)
          ? DiscographyItem(
              id: '', // id will be generated by Firestore on add
              title: title,
              embedHtml: embed,
              // Use a large, time-based default so new items sort to the end by ascending 'order'
              order: DateTime.now().millisecondsSinceEpoch,
            )
          : widget.item!.copyWith(
              title: title,
              embedHtml: embed,
            );

      Navigator.of(context).pop(result);
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: Text(widget.item == null ? 'Add Discography Item' : 'Edit Discography Item'),
      content: Form(
        key: _formKey,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            TextFormField(
              controller: _titleController,
              decoration: const InputDecoration(labelText: 'Title', border: OutlineInputBorder()),
              validator: (value) => (value?.isEmpty ?? true) ? 'Please enter a title' : null,
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: _embedController,
              decoration: const InputDecoration(labelText: 'Embed HTML', border: OutlineInputBorder(), alignLabelWithHint: true),
              maxLines: 5,
              validator: (value) => (value?.isEmpty ?? true) ? 'Please enter the embed HTML' : null,
            ),
          ],
        ),
      ),
      actions: [
        TextButton(onPressed: () => Navigator.of(context).pop(), child: const Text('Cancel')),
        ElevatedButton(onPressed: _onSave, child: const Text('Save')),
      ],
    );
  }
}